name: Demande de fonctionnalité
description: Proposer une amélioration ou une nouvelle fonctionnalité
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: Merci pour votre suggestion !

  - type: textarea
    id: probleme
    attributes:
      label: Quel problème cela résout-il ?
      placeholder: J'aimerais pouvoir inclure des polices personnalisées, car…
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Solution envisagée
      placeholder: Une nouvelle directive #manifest.font(...) pour embarquer les fichiers .ttf.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives envisagées
      description: Y a-t-il d'autres façons de résoudre ce problème ?
    validations:
      required: false
